#!/usr/bin/env python

# Prints out the number of lines of python code found in the current 
# directory tree.

import os
import fnmatch


def walk(pattern='*'):
    for path, subdirs, files in os.walk('.'):
        for name in files:
            if fnmatch.fnmatch(name, pattern):
                yield os.path.join(path, name)


def main():
    count_mini, count_maxi = 0, 0
    num_files = 0
    for fspec in walk(pattern='*.py'):
        num_files += 1
        skip = False
        for line in open(fspec):
            count_maxi += 1

            line = line.strip()
            if line:
                if line.startswith('#'):
                    continue
                if line.startswith('"""'):
                    skip = not skip
                    continue
                if not skip:
                    count_mini += 1

    print '# files:', num_files
    print 'LOC:', count_maxi
    print 'sLOC:', count_mini


if __name__ == '__main__':
    main()
